spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bharathi
    username: ${username}
    password: ${password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
healthcare:
  management:
   user:
     uri: http://localhost:8081/Users
     name: Healthcare-Management-User-API 
   patient:
     uri: http://localhost:8080/Patient
     name: Healthcare-Management-Patient-API
   vitalsign:
     uri: http://localhost:8082/VitalSign
     name: Healthcare-Management-VitalSign-API 
   configclient:
     uri: http://localhost:8888
     name: config-client
   vault:
     uri: http://localhost:8200
