server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bharathi
    username: ${username}
    password: ${password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
healthcare:
  patient:
    uri: http://localhost:8080/Patient
    name: Healthcare-Management-Patient-API 
  user:
    uri: http://localhost:8081/Users
    name: Healthcare-Management-User-API 
